export const Feasts = [
  'عيد الميلاد المجيد',
  'عيد الصعود',
  'سبت لعازر',
  'أحد الشعانين',
  'الأثنين من البصخة المُقدَّسة',
  'ثلاثاء من البصخة المُقدَّسة',
  'الأربعاء من البصخة المُقدَّسة',
  'الخميس من البصخة المُقدَّسة',
  'الجمعة العظيمة من البصخة المُقدَّسة',
  'عيد الدخول إلى الهيكل',
  'عيد مجيء المسيح إلى أرض مصر',
  'عيد البشارة',
  'عيد الصليب',
  'صوم نينوي',
  'يونان',
  'برامون الميلاد المجيد',
  'برامون عيد الظهور الإلهي',
  'عيد الظهور الإلهي',
  'عرس قانا',
  'السبت قبل الصوم الكبير',
  'الأحد قبل الصوم الكبير',
  'أحد القيامة',
  'عيد النيروز - عيد رأس السنة القبطية',
];

export const EFeast = {
  NONE: -1,
  Christmas: 1,
  Ascension: 2,
  LazarusSaturday: 3,
  PalmSunday: 4,
  PaschaMonday: 5,
  PaschaTuesday: 6,
  PaschaWednesday: 7,
  PaschaThursday: 8,
  PaschaFriday: 9,
  TempleEntrance: 10,
  EgyptEntrance: 11,
  Annunciation: 12,
  Cross: 13,
  FastOfNinevah1: 14,
  FastOfNinevah2: 142,
  FastOfNinevah3: 143,
  Jonas: 15,
  NativityParamoun: 16,
  TheophanyParamoun: 17,
  Theophany: 18,
  WeddingOfCana: 19,
  GreatLentPreparationSaturday: 20,
  GreatLentPreparationSunday: 21,
  Easter: 22,
  Nayrouz: 23,
};
